# -*- coding: utf-8 -*-
"""Tugas asd

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wbyimMd5NanFzJVt96_CFXW8upZhwaN6
"""

stack = []
max_size = int(input("Masukkan Ukuran Maksimal Stack: "))

def isEmpty():
	if len(stack) == 0:
		print("Stack Kosong.")
		return True
	return False
	
def isFull():
	if len(stack) == max_size:
		print("Stack Penuh.")
		return True
	return False
		
def pop():
	if isEmpty() == False:
		print(stack.pop(), "terhapus.")

def push():
	if isFull() == False:
		x = input("Masukkan Item Baru: ")
		stack.append(x)
		print(x, "ditambahkan.")
		
def peek():
	if isEmpty() == False:
		print("Top: ", stack[-1])


p = 0
while p != '6':
    print('''\n1. Push => Menambah Item
2. Pop => Menghapus Item
3. Peek => Melihat Item Teratas
4. Empty => Memeriksa Apakah Stack Penuh
5. Size => Melihat Ukuran Stack''')
    p = input("Ketik 6 untuk berhenti\nMasukkan Perintah: ")
    print()
    
    if p == '1':
    	push()
    elif p == '2':
    	pop()
    elif p == '3':
    	peek()
    elif p == '4':
    	if isEmpty() == False:
    		print("Stack memiliki isi.")
    elif p == '5':
    	print("Ukuran stack saat ini: ", len(stack), "\nUkuran maksimal stack: ", max_size)

queue = []
max_size = int(input("Masukkan Ukuran Maksimal Queue: "))

def isEmpty():
	if len(queue) == 0:
		print("Queue Kosong.")
		return True
	return False
	
def isFull():
	if len(queue) == max_size:
		print("Queue Penuh.")
		return True
	return False
		
def dequeue():
	if isEmpty() == False:
		print(queue.pop(0), "terhapus dari queue.")

def enqueue():
	if isFull() == False:
		x = input("Masukkan Antrian Baru: ")
		queue.append(x)
		print(x, "ditambahkan ke queue.")

p = 0
while p != '6':
    print('''\n1. Enqueue => Menambah Antrian
2. Dequeue => Menghapus dari Antrian
3. Full => Memeriksa Apakah Queue Penuh
4. Size => Melihat Ukuran Queue''')
    p = input("Ketik 6 untuk berhenti\nMasukkan Perintah: ")
    print()
    
    if p == '1':
    	enqueue()
    elif p == '2':
    	dequeue()
    elif p == '3':
    	if isFull() == False:
   	  	print("Queue belum penuh.")
    elif p == '4':
    	print("Ukuran queue saat ini: ", len(queue), "\nUkuran maksimal queue: ", max_size)