# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1A5NSF_GQcQ7JYyGIKNK6zEdjXouotJjq

Cara menampilkan kode pada python
"""

Print("haerul")

"""Aturan dasar"""

#ini fungsi print
print("haerul")

"""Tipe data pada python"""

Nilai = 4==4
print("Nilai")

Nma = "Haerul"
print(Nma)

Angka = 10
print(Angka)
type(Angka)

Angka = 1.3
print(Angka)
type(Angka)

"""Variable"""

Nilai = 40

"""Cara mengecek type data"""





"""Percabangan"""

Nilai = 10 
if Nilai == 10:
   print("itu adalah angka sepuluh")
Else:

"""Input dan masukan user"""

