# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1A5NSF_GQcQ7JYyGIKNK6zEdjXouotJjq

Cara menampilkan kode pada python
"""

Print("haerul")

"""Aturan dasar"""

#ini fungsi print
print("haerul")

"""Tipe data pada python"""

Nilai = 4==4
print("Nilai")

Nma = "Haerul"
print(Nma)

Angka = 10
print(Angka)
type(Angka)

Angka = 1.3
print(Angka)
type(Angka)

"""Variable"""

Nilai = 40

"""Cara mengecek type data"""





"""Percabangan"""

Nilai = 10 
if Nilai == 10:
   print("itu adalah angka sepuluh")
else:
   print("salah")



#informasi gaji karyawan
print("Nama : HAERUL (D0221367)")
gaji_pokok = 1000000
print("gaji pokok : Rp", gaji_pokok)
gaji_lembur = 5000 * 67
print("gaji lembur : Rp", gaji_lembur)
gaji_kotor = gaji_pokok + gaji_lembur
print("gaji kotor : Rp", gaji_kotor)
pajak = 10/100
print("pajak :", pajak)
Potongan = pajak * gaji_lembur
print("potongan : ", potongan)
print("gaji bersihnya itu : Rp," gaji_kotor - Potongan)